

name: Test project workflow with Node.js

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm install
  test_security:
      runs-on: ubuntu-latest
      needs: test_project
      steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - run: npm audit
  test_project:
      runs-on: ubuntu-latest
      needs: install_dependencies
      steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - run: npm install
      - run: npm test
  build:
        runs-on: ubuntu-latest
        steps:
          - name: Deploy to production
            uses: johnbeynon/render-deploy-action@v0.0.8
            with:
              service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
              api-key: ${{ secrets.MY_RENDER_API_KEY }}
              

  