

name: Test project workflow with Node.js

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm install
    # - run: npm run test
    # - run: npm run start
    
  test_run_tests:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Restore node modules
      uses: actions/download-artifact@v3
      with:
        name: node_modules
        path: node_modules
    - run: npm test